# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhishingCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_name", models.CharField(max_length=255)),
                (
                    "target_brand",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("source_urls", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phishing_campaigns",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "phishing_campaigns",
                "ordering": ["-first_seen", "-threat_level"],
            },
        ),
        migrations.CreateModel(
            name="PhishingMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.JSONField(default=list)),
                ("target_brands", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("alert_on_new_domain", models.BooleanField(default=True)),
                ("alert_on_new_campaign", models.BooleanField(default=True)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phishing_monitors",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "phishing_monitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhishingDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "target_brand",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registrar", models.CharField(blank=True, max_length=255, null=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains",
                        to="phishing.phishingcampaign",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phishing_domains",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "phishing_domains",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="phishing_do_domain_1374bd_idx"
                    ),
                    models.Index(
                        fields=["is_active", "last_seen"],
                        name="phishing_do_is_acti_df6be2_idx",
                    ),
                ],
            },
        ),
    ]
