# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RansomwareSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(db_index=True, max_length=255)),
                (
                    "onion_address",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("clearnet_url", models.URLField(blank=True, null=True)),
                ("site_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("seized", "Seized"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_check", models.DateTimeField(blank=True, null=True)),
                ("check_count", models.IntegerField(default=0)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_post_count", models.IntegerField(default=0)),
                ("current_post_count", models.IntegerField(default=0)),
                ("has_new_posts", models.BooleanField(default=False)),
                ("source", models.CharField(default="ransomware.live", max_length=100)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ransomware_sites",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ransomware_sites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RansomwarePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "victim_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("discovered_date", models.DateTimeField(auto_now_add=True)),
                ("is_new", models.BooleanField(default=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("removed_date", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="monitoring.ransomwaresite",
                    ),
                ),
            ],
            options={
                "db_table": "ransomware_posts",
                "ordering": ["-posted_date", "-discovered_date"],
            },
        ),
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.CharField(max_length=255)),
                ("repo_name", models.CharField(max_length=255)),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField()),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "monitor_frequency",
                    models.CharField(
                        choices=[
                            ("5min", "Every 5 minutes"),
                            ("15min", "Every 15 minutes"),
                            ("30min", "Every 30 minutes"),
                            ("1hour", "Every hour"),
                            ("6hours", "Every 6 hours"),
                            ("12hours", "Every 12 hours"),
                            ("24hours", "Every 24 hours"),
                        ],
                        default="1hour",
                        max_length=20,
                    ),
                ),
                (
                    "last_commit_sha",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("last_commit_date", models.DateTimeField(blank=True, null=True)),
                ("total_commits", models.IntegerField(default=0)),
                ("total_cves_found", models.IntegerField(default=0)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_check", models.DateTimeField(blank=True, null=True)),
                ("check_error", models.TextField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_repositories",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "github_repositories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubCVERef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cve_id", models.CharField(db_index=True, max_length=50)),
                ("file_path", models.CharField(max_length=1000)),
                ("commit_sha", models.CharField(max_length=40)),
                ("commit_date", models.DateTimeField()),
                ("commit_message", models.TextField(blank=True, null=True)),
                ("branch", models.CharField(default="main", max_length=100)),
                ("url", models.URLField()),
                ("is_new", models.BooleanField(default=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_refs",
                        to="monitoring.githubrepository",
                    ),
                ),
            ],
            options={
                "db_table": "github_cve_refs",
                "ordering": ["-commit_date"],
            },
        ),
        migrations.AddIndex(
            model_name="ransomwaresite",
            index=models.Index(
                fields=["group_name"], name="ransomware__group_n_8d2c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwaresite",
            index=models.Index(
                fields=["onion_address"], name="ransomware__onion_a_9dea61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwaresite",
            index=models.Index(
                fields=["is_active", "status"], name="ransomware__is_acti_57e6f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwaresite",
            index=models.Index(
                fields=["last_checked_at"], name="ransomware__last_ch_eea7bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwarepost",
            index=models.Index(
                fields=["site", "posted_date"], name="ransomware__site_id_eff2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwarepost",
            index=models.Index(
                fields=["post_id", "site"], name="ransomware__post_id_a5d107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransomwarepost",
            index=models.Index(
                fields=["is_new", "discovered_date"],
                name="ransomware__is_new_5d2309_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ransomwarepost",
            unique_together={("site", "post_id")},
        ),
        migrations.AddIndex(
            model_name="githubrepository",
            index=models.Index(
                fields=["full_name"], name="github_repo_full_na_6144fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubrepository",
            index=models.Index(
                fields=["is_active", "monitor_frequency"],
                name="github_repo_is_acti_1a24f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubrepository",
            index=models.Index(
                fields=["last_check_at"], name="github_repo_last_ch_784310_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubcveref",
            index=models.Index(
                fields=["repository", "cve_id"], name="github_cve__reposit_8e6d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubcveref",
            index=models.Index(
                fields=["cve_id", "is_new"], name="github_cve__cve_id_342bc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="githubcveref",
            index=models.Index(
                fields=["commit_date"], name="github_cve__commit__0d05d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="githubcveref",
            unique_together={("repository", "cve_id", "commit_sha")},
        ),
    ]
