# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreachMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.JSONField(default=list)),
                ("industries", models.JSONField(default=list)),
                ("countries", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("alert_on_new_breach", models.BooleanField(default=True)),
                ("alert_on_high_severity", models.BooleanField(default=True)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "breach_monitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataBreach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("breach_name", models.CharField(max_length=255)),
                ("affected_organization", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("breach_date", models.DateField(blank=True, null=True)),
                ("discovered_date", models.DateField(blank=True, null=True)),
                ("disclosed_date", models.DateField(blank=True, null=True)),
                ("records_affected", models.BigIntegerField(blank=True, null=True)),
                ("data_types", models.JSONField(default=list)),
                (
                    "breach_type",
                    models.CharField(
                        choices=[
                            ("hack", "Hack"),
                            ("insider", "Insider Threat"),
                            ("accidental", "Accidental Exposure"),
                            ("physical", "Physical Theft"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_breaches",
                "ordering": ["-breach_date", "-created_at"],
            },
        ),
    ]
