# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("breaches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databreach",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_breaches",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="breachmonitor",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breach_monitors",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="databreach",
            index=models.Index(
                fields=["breach_date"], name="data_breach_breach__a72664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="databreach",
            index=models.Index(
                fields=["affected_organization"], name="data_breach_affecte_ec29a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="databreach",
            index=models.Index(
                fields=["industry", "breach_date"],
                name="data_breach_industr_f213d1_idx",
            ),
        ),
    ]
