# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("key_prefix", models.CharField(max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "health_checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("max_scans_per_month", models.IntegerField(default=100)),
                ("max_api_requests_per_month", models.IntegerField(default=10000)),
                ("max_monitored_domains", models.IntegerField(default=5)),
                ("max_alert_rules", models.IntegerField(default=10)),
                ("retention_days", models.IntegerField(default=30)),
                ("has_api_access", models.BooleanField(default=False)),
                ("has_webhooks", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("has_custom_integrations", models.BooleanField(default=False)),
                ("has_advanced_analytics", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_users",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_api_keys",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization",
                        to="core.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnionSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "onion_address",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace"),
                            ("forum", "Forum"),
                            ("leak_site", "Leak Site"),
                            ("ransomware", "Ransomware Group"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onion_sites",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "onion_sites",
                "ordering": ["-last_checked", "-first_seen"],
            },
        ),
        migrations.CreateModel(
            name="OnionDataPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_title", models.CharField(max_length=500)),
                ("post_content", models.TextField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("discovered_date", models.DateTimeField(auto_now_add=True)),
                ("data_types", models.JSONField(default=list)),
                (
                    "affected_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("record_count", models.BigIntegerField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "onion_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_posts",
                        to="core.onionsite",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onion_data_posts",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "onion_data_posts",
                "ordering": ["-posted_date", "-discovered_date"],
            },
        ),
        migrations.CreateModel(
            name="LeakedCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "username",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "password_plain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "breach_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("leak_date", models.DateField(blank=True, null=True)),
                ("discovered_date", models.DateTimeField(auto_now_add=True)),
                ("data_types", models.JSONField(default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_exposed", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaked_credentials",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "leaked_credentials",
                "ordering": ["-discovered_date", "-leak_date"],
            },
        ),
        migrations.CreateModel(
            name="C2Server",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(default="http", max_length=20)),
                ("c2_family", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "malware_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("asn", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="c2_servers",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "c2_servers",
                "ordering": ["-last_seen", "-threat_level"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("api_call", "API Call"),
                            ("config_change", "Configuration Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("api_request", "API Request"),
                            ("scan", "Security Scan"),
                            ("webhook", "Webhook"),
                            ("data_export", "Data Export"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("metadata", models.JSONField(default=dict)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_metrics",
                        to="core.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "usage_metrics",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="usage_metri_organiz_9776fe_idx",
                    ),
                    models.Index(
                        fields=["api_key", "date"],
                        name="usage_metri_api_key_374f1b_idx",
                    ),
                ],
                "unique_together": {("organization", "metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("ransomware", "Ransomware"),
                            ("data_breach", "Data Breach"),
                            ("phishing", "Phishing"),
                            ("c2", "C2 Server"),
                            ("malware", "Malware"),
                            ("apt", "APT"),
                            ("vulnerability", "Vulnerability"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("indicators", models.JSONField(default=dict)),
                ("affected_countries", models.JSONField(default=list)),
                ("affected_industries", models.JSONField(default=list)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_intelligence",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "threat_intelligence",
                "ordering": ["-severity", "-first_seen", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["threat_type", "severity"],
                        name="threat_inte_threat__6eca19_idx",
                    ),
                    models.Index(
                        fields=["severity", "first_seen"],
                        name="threat_inte_severit_604ba4_idx",
                    ),
                    models.Index(
                        fields=["is_verified", "created_at"],
                        name="threat_inte_is_veri_29ba9e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="onionsite",
            index=models.Index(
                fields=["onion_address", "is_active"],
                name="onion_sites_onion_a_06df8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onionsite",
            index=models.Index(
                fields=["site_type", "is_active"], name="onion_sites_site_ty_2b6e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oniondatapost",
            index=models.Index(
                fields=["onion_site", "posted_date"],
                name="onion_data__onion_s_2e330d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oniondatapost",
            index=models.Index(
                fields=["affected_organization", "posted_date"],
                name="onion_data__affecte_39ef95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oniondatapost",
            index=models.Index(
                fields=["discovered_date"], name="onion_data__discove_bc6c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leakedcredential",
            index=models.Index(fields=["email"], name="leaked_cred_email_326841_idx"),
        ),
        migrations.AddIndex(
            model_name="leakedcredential",
            index=models.Index(
                fields=["username"], name="leaked_cred_usernam_1eca7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leakedcredential",
            index=models.Index(fields=["domain"], name="leaked_cred_domain_6c5b41_idx"),
        ),
        migrations.AddIndex(
            model_name="leakedcredential",
            index=models.Index(
                fields=["breach_source", "leak_date"],
                name="leaked_cred_breach__956293_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leakedcredential",
            index=models.Index(
                fields=["is_exposed", "discovered_date"],
                name="leaked_cred_is_expo_3fcb04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="c2server",
            index=models.Index(
                fields=["domain", "is_active"], name="c2_servers_domain_e53b84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c2server",
            index=models.Index(
                fields=["ip_address", "is_active"], name="c2_servers_ip_addr_7d44a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c2server",
            index=models.Index(
                fields=["c2_family", "threat_level"],
                name="c2_servers_c2_fami_895195_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "created_at"],
                name="audit_logs_organiz_af0d8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"], name="audit_logs_user_id_fbfd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="audit_logs_action__94af82_idx",
            ),
        ),
    ]
