# Generated by Django 4.2.26 on 2025-11-24 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("url", "URL"),
                            ("subdomain", "Subdomain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scan_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("next_scan_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_targets",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "scan_targets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("vulnerability", "Vulnerability Scan"),
                            ("ssl", "SSL/TLS Scan"),
                            ("dns", "DNS Scan"),
                            ("port", "Port Scan"),
                            ("web", "Web Application Scan"),
                            ("full", "Full Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("vulnerabilities_critical", models.IntegerField(default=0)),
                ("vulnerabilities_high", models.IntegerField(default=0)),
                ("vulnerabilities_medium", models.IntegerField(default=0)),
                ("vulnerabilities_low", models.IntegerField(default=0)),
                (
                    "risk_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("results", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_scans",
                        to="core.organization",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="scanner.scantarget",
                    ),
                ),
            ],
            options={
                "db_table": "security_scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "affected_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("references", models.JSONField(default=list)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="scanner.securityscan",
                    ),
                ),
            ],
            options={
                "db_table": "vulnerabilities",
                "ordering": ["-severity", "-cvss_score", "title"],
                "indexes": [
                    models.Index(
                        fields=["scan", "severity"],
                        name="vulnerabili_scan_id_d13ec1_idx",
                    ),
                    models.Index(
                        fields=["cve_id"], name="vulnerabili_cve_id_c3a712_idx"
                    ),
                    models.Index(
                        fields=["is_resolved", "severity"],
                        name="vulnerabili_is_reso_17e7f7_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="securityscan",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="security_sc_organiz_f0d734_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityscan",
            index=models.Index(
                fields=["target", "created_at"], name="security_sc_target__3aee1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityscan",
            index=models.Index(
                fields=["scan_type", "status"], name="security_sc_scan_ty_506c84_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scantarget",
            unique_together={("organization", "target_value")},
        ),
    ]
