# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RansomwareGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("aliases", models.JSONField(default=list)),
                ("description", models.TextField(blank=True, null=True)),
                ("first_seen", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ransomware_groups",
                "ordering": ["-threat_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="RansomwareMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.JSONField(default=list)),
                ("industries", models.JSONField(default=list)),
                ("countries", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("alert_on_new_incident", models.BooleanField(default=True)),
                ("alert_on_leak", models.BooleanField(default=True)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(blank=True, to="ransomware.ransomwaregroup"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ransomware_monitors",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ransomware_monitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RansomwareIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("victim_name", models.CharField(max_length=255)),
                (
                    "victim_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "victim_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("announced_date", models.DateField()),
                ("leak_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("announced", "Announced"),
                            ("leaked", "Leaked"),
                            ("resolved", "Resolved"),
                        ],
                        default="announced",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("data_types", models.JSONField(default=list)),
                (
                    "estimated_impact",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="ransomware.ransomwaregroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ransomware_incidents",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ransomware_incidents",
                "ordering": ["-announced_date"],
                "indexes": [
                    models.Index(
                        fields=["announced_date"], name="ransomware__announc_3969cf_idx"
                    ),
                    models.Index(
                        fields=["group", "announced_date"],
                        name="ransomware__group_i_c8e2ff_idx",
                    ),
                    models.Index(
                        fields=["victim_industry"],
                        name="ransomware__victim__36b420_idx",
                    ),
                ],
            },
        ),
    ]
