# Generated by Django 4.2.26 on 2025-11-24 08:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cve_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "cvss_v3_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "cvss_v2_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "cvss_v3_vector",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("affected_products", models.JSONField(default=list)),
                ("affected_versions", models.JSONField(default=list)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                ("has_exploit", models.BooleanField(default=False)),
                ("exploit_available", models.BooleanField(default=False)),
                ("poc_available", models.BooleanField(default=False)),
                ("poc_url", models.URLField(blank=True, null=True)),
                ("github_repo", models.URLField(blank=True, null=True)),
                (
                    "exploit_maturity",
                    models.CharField(
                        choices=[
                            ("unproven", "Unproven"),
                            ("proof_of_concept", "Proof of Concept"),
                            ("functional", "Functional"),
                            ("high", "High"),
                            ("not_defined", "Not Defined"),
                        ],
                        default="not_defined",
                        max_length=20,
                    ),
                ),
                ("cwe_id", models.CharField(blank=True, max_length=50, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
                ("discovered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("analyzing", "Analyzing"),
                            ("exploited", "Exploited"),
                            ("patched", "Patched"),
                            ("disputed", "Disputed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_publicly_exploited", models.BooleanField(default=False)),
                ("references", models.JSONField(default=list)),
                ("advisory_url", models.URLField(blank=True, null=True)),
                ("mitre_url", models.URLField(blank=True, null=True)),
                ("nvd_url", models.URLField(blank=True, null=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cves",
                        to="core.organization",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_cves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cves",
                "ordering": ["-published_date", "-cvss_v3_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVEComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_verified_expert", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cve.cve",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cve_comments",
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(fields=["cve_id"], name="cves_cve_id_cce98d_idx"),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(
                fields=["severity", "cvss_v3_score"], name="cves_severit_4d1cc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(
                fields=["has_exploit", "exploit_available"],
                name="cves_has_exp_549679_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(
                fields=["status", "created_at"], name="cves_status_d2f0c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(
                fields=["published_date"], name="cves_publish_801605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=models.Index(fields=["vendor"], name="cves_vendor_10b17f_idx"),
        ),
    ]
